name: npobox
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  carousel_slider: 4.1.1
  lottie: 1.3.0
  introduction_screen: ^3.0.2
  get_storage: ^2.0.3
  logger: ^1.1.0
  url_launcher: 6.1.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/lottie/
  uses-material-design: true

